myshopping/goods/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^(?P<store_id>\d+)/goods_upload/$', views.goods_upload, name='goods_upload'),
    url(r'^(?P<goods_id>\d+)/goods_info/$', views.goods_info, name='goods_info'),
    url(r'^goodstype/$', views.goodstype, name='goodstype'),
    url(r'^man_goods/$', views.man_goods, name='man_goods'),
    url(r'^women_goods/$', views.women_goods, name='women_goods'),
    url(r'^children_goods/$', views.children_goods, name='children_goods'),
]

myshopping/myshopping/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
import xadmin
from xadmin.plugins import xversion
xadmin.autodiscover()
xversion.register_models()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^search/',include("haystack.urls")), # 配置检索的路由
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^stores/', include('stores.urls', namespace='stores')),
    url(r'^goods/', include('goods.urls', namespace='goods')),
    url(r'^shopcart/', include('shopcart.urls', namespace='shopcart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^', include('common.urls', namespace='common')),
]

myshopping/orders/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # 结算确认，检查收货地址
    url(r'order_confirm/$', views.order_confirm, name='order_confirm'),
    # 结算付款
    url(r'order_pay/$', views.order_pay, name='order_pay'),
    # 生成订单
    url(r'order_done/$', views.order_done, name='order_done'),
    # 查看所有订单
    url(r'order_list/$', views.order_list, name='order_list'),
    # 查看单个订单
    url(r'(?P<order_id>\d+)/order_info/$', views.order_info, name='order_info'),

]

myshopping/shopcart/urls.py
from django.conf.urls import url

from . import views

app_name = 'shopcart'

urlpatterns = [
    url(r'^(?P<goods_id>\d+)/(?P<count>\d+)/shop_cart_add/$', views.shop_cart_add, name='shop_cart_add'),
    url(r'^shop_cart_info/$', views.shop_cart_info, name='shop_cart_info'),
    url(r'^(?P<goods_id>\d+)/shop_cart_del/$', views.shop_cart_del, name='shop_cart_del'),
    url(r'^(?P<goods_id>\d+)/(?P<i>\d+)/shop_cart_update/$', views.shop_cart_update, name='shop_cart_update'),
]

myshopping/goods/models.py
from django.db import models

# Create your models here.
import stores


class GoodsType(models.Model):
    """
    商品类型
    """
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    cover = models.ImageField(upload_to='static/images/goodstype/', default='static/images/goodstype/default.jpg')
    intro = models.TextField()

    parent = models.ForeignKey('self', null=True, blank=True)


class Goods(models.Model):
    """
    商品数据模型
    """
    id = models.AutoField(primary_key=True, verbose_name='商品编号')
    name = models.CharField(max_length=50, verbose_name='商品名称')
    price = models.FloatField(verbose_name='商品价格')
    stock = models.IntegerField(verbose_name='商品库存')
    sales = models.IntegerField(verbose_name="商品销量")
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='上架时间')
    intro = models.TextField(verbose_name='商品描述')

    goodstype = models.ForeignKey(GoodsType, on_delete=models.CASCADE, verbose_name='商品类型')
    store = models.ForeignKey(stores.models.Store, on_delete=models.CASCADE, verbose_name='所属商店')

    class Meta:
        # 末尾不加s
        verbose_name_plural = '商品'
        # 末尾加s
        # verbose_name = '商品'


class GoodsImages(models.Model):
    """
    商品图片
    """
    id = models.AutoField(primary_key=True)
    path = models.ImageField(upload_to='static/images/goods/')
    goods = models.ForeignKey(Goods, on_delete=models.CASCADE)

myshopping/shopcart/models.py
from django.db import models
# 导入django框架内置的用户模块
from django.contrib.auth.models import User

import goods


class ShopCart(models.Model):
    """
    购物车模型
    """
    id = models.AutoField(primary_key=True)
    goods = models.ForeignKey(goods.models.Goods, on_delete=models.CASCADE, verbose_name='商品名称')
    count = models.IntegerField(default=10, verbose_name='商品数量')
    total = models.FloatField()
    users = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='用户')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='添加购物车时间')

myshopping/shopcart/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.db.models import Q, F
# django内置的装饰器函数，用户登录后才能访问
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse


import goods
from . import models
import shopcart


@login_required
def shop_cart_add(request, goods_id, count):
    """
    添加商品到购物车功能
    :param request:
    :param goods_id: 商品id
    :param count: 商品数量
    :return:
    """
    # 得到用户购买的商品
    _goods = goods.models.Goods.objects.get(pk=goods_id)
    try:
        # 查询当前用户的购物车是否包含该商品
        shop_cart = models.ShopCart.objects.get(Q(users=request.user) & Q(goods=_goods))
        shop_cart.count += int(count)
        shop_cart.total = float(shop_cart.count) * _goods.price
        shop_cart.save()
    except Exception as e:
        # 查询关键购物对象，添加到购物车中
        shop_cart = models.ShopCart(goods=_goods, count=count, users=request.user)
        shop_cart.total = float(count) * _goods.price
        shop_cart.save()
        print("--------------------->", e)

    shop_cart_list = models.ShopCart.objects.filter(users=request.user).order_by('-add_time')
    return render(request, "shopcart/shop_cart_info.html", {'shop_cart_list': shop_cart_list})

    # return HttpResponse('商品添加成功！')


@login_required
def shop_cart_info(request):
    """
    查看购物车
    :param request:
    :return:
    """
    shop_cart_list = models.ShopCart.objects.filter(users=request.user).order_by('-add_time')
    return render(request, "shopcart/shop_cart_info.html", {'shop_cart_list': shop_cart_list})


@login_required
def shop_cart_del(request, goods_id):
    """
    删除购物车商品
    :param request:
    :return:
    """
    _goods = shopcart.models.ShopCart.objects.get(pk=goods_id)
    print(_goods)
    _goods.delete()
    return HttpResponse('成功')


@login_required
def shop_cart_update(requsest, goods_id, i):
    """
    更该购物车商品信息
    :param requsest:
    :param goods_id:
    :return:
    """
    _goods = shopcart.models.ShopCart.objects.get(pk=goods_id)
    # print(_goods)
    _goods.count = i
    things = goods.models.Goods.objects.get(pk=_goods.goods_id)
    _goods.total = float(i) * things.price
    _goods.save()
    return HttpResponse('成功')

myshopping/shopcart/templates/shopcart/shop_cart_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>购物车添加</title>
</head>
<body>

</body>
</html>

myshopping/shopcart/templates/shopcart/shop_cart_info.html
{% extends 'base.html'%}
{% block lunbo %}
{% load static %}
<link rel="stylesheet" href="{% static 'shopcart/css/shop_cart_info.css'%}">
<script src="{% static 'shopcart/js/app/shop_cart_info.js'%}"></script>
<div class="box111">
<div class="shop_card_box box222">
    <form action="{% url 'orders:order_confirm' %}" method="POST">
        {% csrf_token %}
    <input type="checkbox" style="width:20px;height: 20px;" name="" id="check_all">全选
    {% for shop_cart in shop_cart_list %}
    <div class="shop_cart_item ">
        <div class="col-md-12">

            <div class="col-md-3 left1">
                <input type="checkbox" style="width:20px;height: 20px;" name="buy_goods_id" value="{{ shop_cart.id }}">
                <img style="width: 150px;height: 150px;" src="/{{shop_cart.goods.goodsimages_set.all.first.path}}" alt="">
            </div>
            <div class="col-md-9 ">
                <p class="goods_name size1">商品名称：{{shop_cart.goods.name}}</p>
                <p class="good_price size1" data-m="{{shop_cart.goods.price}}">商品价格：{{shop_cart.goods.price}}</p>
                <div class="amount_box">
                    <span class="reduce" down_goods_id="{{shop_cart.id}}" style="cursor: pointer">-</span>
                    <input type="text" name="count" value="{{shop_cart.count}}" class="sum">
                    <span class="add" up_goods_id="{{shop_cart.id}}" style="cursor: pointer">+</span>
                </div>
                <p class="subtotal size1">总价：<span>{{shop_cart.total}}</span></p>
            </div>
            <a class="del-cart" style=" margin-left: 30px;cursor:pointer;" goods_id="{{shop_cart.id}}">删除</a>
    </div>
        </div>
        <hr>
    {% empty %}
    <div class="shop_cart_item">购物车为空!</div>
    {% endfor %}
        <button type="submit" class="btn btn-danger">结算</button>

    </form>
</div>
</div>
{% endblock %}
{% block content %}{% endblock %}
{% block content2 %}{% endblock %}