myshopping/common/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^.*$', views.index, name='index'),
]

myshopping/goods/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^(?P<store_id>\d+)/goods_upload/$', views.goods_upload, name='goods_upload'),
    url(r'^(?P<goods_id>\d+)/goods_info/$', views.goods_info, name='goods_info'),
    url(r'^goodstype/$', views.goodstype, name='goodstype'),
    url(r'^man_goods/$', views.man_goods, name='man_goods'),
    url(r'^women_goods/$', views.women_goods, name='women_goods'),
    url(r'^children_goods/$', views.children_goods, name='children_goods'),
]

myshopping/myshopping/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
import xadmin
from xadmin.plugins import xversion
xadmin.autodiscover()
xversion.register_models()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^search/',include("haystack.urls")), # 配置检索的路由
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^stores/', include('stores.urls', namespace='stores')),
    url(r'^goods/', include('goods.urls', namespace='goods')),
    url(r'^shopcart/', include('shopcart.urls', namespace='shopcart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^', include('common.urls', namespace='common')),
]

myshopping/orders/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # 结算确认，检查收货地址
    url(r'order_confirm/$', views.order_confirm, name='order_confirm'),
    # 结算付款
    url(r'order_pay/$', views.order_pay, name='order_pay'),
    # 生成订单
    url(r'order_done/$', views.order_done, name='order_done'),
    # 查看所有订单
    url(r'order_list/$', views.order_list, name='order_list'),
    # 查看单个订单
    url(r'(?P<order_id>\d+)/order_info/$', views.order_info, name='order_info'),

]

myshopping/stores/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^store_add/$', views.store_add, name='store_add'),
    url(r'^store_list/', views.store_list, name='store_list'),
    url(r'^(?P<s_id>\d+)/store_info/', views.store_info, name='store_info'),
    url(r'^(?P<store_id>\d+)/store_update/', views.store_update, name='store_update'),
    url(r'^(?P<store_id>\d+)/store_close/', views.store_close, name='store_close'),
    url(r'^(?P<store_id>\d+)/store_del/', views.store_del, name='store_del'),
    url(r'^store_update/', views.store_update, name='store_update'),
]

myshopping/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^register/$', views.user_register, name='user_register'),
    url(r'^send_message/$', views.send_message, name='send_message'),
    url(r'^login/$', views.user_login, name='user_login'),
    url(r'^user_info/$', views.user_info, name='user_info'),
    url(r'^add_address/$', views.add_address, name='add_address'),
    url(r'^delete_address(?P<addr_id>\d+)/$', views.delete_address, name='delete_address'),
    url(r'^address_list/$', views.address_list, name='address_list'),
    url(r'^logout/$', views.user_logout, name='user_logout'),
]

myshopping/goods/models.py
from django.db import models

# Create your models here.
import stores


class GoodsType(models.Model):
    """
    商品类型
    """
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    cover = models.ImageField(upload_to='static/images/goodstype/', default='static/images/goodstype/default.jpg')
    intro = models.TextField()

    parent = models.ForeignKey('self', null=True, blank=True)


class Goods(models.Model):
    """
    商品数据模型
    """
    id = models.AutoField(primary_key=True, verbose_name='商品编号')
    name = models.CharField(max_length=50, verbose_name='商品名称')
    price = models.FloatField(verbose_name='商品价格')
    stock = models.IntegerField(verbose_name='商品库存')
    sales = models.IntegerField(verbose_name="商品销量")
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='上架时间')
    intro = models.TextField(verbose_name='商品描述')

    goodstype = models.ForeignKey(GoodsType, on_delete=models.CASCADE, verbose_name='商品类型')
    store = models.ForeignKey(stores.models.Store, on_delete=models.CASCADE, verbose_name='所属商店')

    class Meta:
        # 末尾不加s
        verbose_name_plural = '商品'
        # 末尾加s
        # verbose_name = '商品'


class GoodsImages(models.Model):
    """
    商品图片
    """
    id = models.AutoField(primary_key=True)
    path = models.ImageField(upload_to='static/images/goods/')
    goods = models.ForeignKey(Goods, on_delete=models.CASCADE)

myshopping/orders/models.py
from django.db import models
from django.contrib.auth.models import User


class MyOrder(models.Model):
    """
    订单的数据模型
    """
    id = models.AutoField(primary_key=True)
    order_time = models.DateTimeField(auto_now_add=True, verbose_name='下单时间')
    address = models.CharField(max_length=255, verbose_name='收货地址')
    total = models.FloatField(verbose_name='总计金额额')

    user = models.ForeignKey(User, on_delete=models.CASCADE)


class MyOrderItem(models.Model):
    """
    订单中的购物对象模型
    """
    id = models.AutoField(primary_key=True)
    goods_img = models.ImageField(upload_to='static/images/goods/')
    goods_name = models.CharField(max_length=255, verbose_name='商品名称')
    goods_price = models.FloatField(verbose_name='商品价格')
    goods_count = models.IntegerField(verbose_name='购买数量')
    goods_subtotal = models.FloatField(verbose_name='小计金额')

    myorder = models.ForeignKey(MyOrder, on_delete=models.CASCADE)

myshopping/orders/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
import shopcart, users

from . import models
import orders


@login_required
def order_confirm(request):
    """
    订单确认
    :param request:
    :return:
    """
    # 获取数据
    buy_goods_id_list = request.POST.getlist('buy_goods_id')
    print(buy_goods_id_list)
    shop_cart_list = shopcart.models.ShopCart.objects.filter(pk__in=buy_goods_id_list)
    # # 计算总金额
    total = 0
    for sc_id in buy_goods_id_list:
        # 查询购物对象
        _shopcart = shopcart.models.ShopCart.objects.get(pk=sc_id)
        total += _shopcart.total
    print(total)
    if len(shop_cart_list) > 0:
        return render(request, 'orders/order_confirm.html', {'shop_cart_list': shop_cart_list, 'total':total})
    else:
        return redirect(reverse('shopcart:shop_cart_info'))


@login_required
def order_pay(request):
    """
    订单支付
    :param request:
    :return:
    """
    pass


@login_required
def order_done(request):
    """
    生成订单
    :param request:
    :return:
    """
    # 获取购买的商品
    shop_cart_list = request.POST.getlist('sc')
    # 获取购买者地址
    addr_id = request.POST['addr_id']
    address = users.models.Address.objects.get(pk=addr_id)
    addr = address.consignee + ";" + address.phone + ";" + address.nation + ";" + address.province\
        + ";" + address.country + ";" + address.street + ";" + address.intro + ";"
    total = 0
    # 生成订单
    myorder = models.MyOrder(user=request.user, address=addr, total=total)
    myorder.save()
    # 创建订单对象
    for sc_id in shop_cart_list:
        # 查询购物对象
        _shopcart = shopcart.models.ShopCart.objects.get(pk=sc_id)
        # 创建订单对像
        order_item = models.MyOrderItem(goods_img=_shopcart.goods.goodsimages_set.first().path, \
                                        goods_name=_shopcart.goods.name,\
                                        goods_price=_shopcart.goods.price,\
                                        goods_count=_shopcart.count,\
                                        goods_subtotal=_shopcart.total,\
                                        myorder=myorder)

        order_item.save()
        # 计算总计金额
        total += _shopcart.total
        print(total)
    # 更新总计金额
    myorder.total = total
    myorder.save()
    # 提交保存订单，跳转订单详情页面
    return redirect(reverse("orders:order_info", kwargs={'order_id': myorder.id}))


@login_required
def order_list(request):
    """
    查看订单列表
    :param request:
    :return:
    """
    order_list = orders.models.MyOrder.objects.filter(user_id=request.user.id)
    return render(request, 'orders/order_list.html', {'order_list': order_list})


@login_required
def order_info(request, order_id):
    """
    查看订单信息
    :param request:
    :return:
    """
    _order = models.MyOrder.objects.get(pk=order_id)
    return render(request, "orders/order_info.html", {"order": _order})

myshopping/orders/templates/orders/order_confirm.html
{% extends 'base.html' %}
{% block lunbo %}
{% load static %}
<!--<link rel="stylesheet" href="{% static 'stores/css/store_add.css' %}">-->
<!--<link rel="stylesheet" href="{% static 'stores/css/store_add.css' %}">-->
<link rel="stylesheet" href="{% static 'orders/css/order_confirm.css'%}">
<div class="container">
    <!--已开店铺-->
    <!--<div class="col-md-12">-->
        <!--<div class="alert alert-success" role="alert">-->
          <!--<a href="{% url 'stores:store_list' %}" class="alert-link"><p style="text-align: center">点击查看您拥有的小店~~~😀</p></a>-->
        <!--</div>-->
    <!--</div>-->
    <form action="{% url 'orders:order_done' %}" method="post">
            <div class="page-header">
          <h1>选择收货地址 <br>
              <small>
                {% csrf_token %}

                <!--
                1. 用户收货地址 : input:radio
                2. 用户购物车结算商品:shop_cart_list
                <!--展示用户所有收货地址-->
                <br />
                {% for sc in shop_cart_list %}
                <input type="hidden" name="sc" value="{{sc.id}}">
                {% endfor %}

                {% for address in shop_cart_list.first.users.address_set.all %}
                {% if address.is_default %}
                    <input type="radio" name="addr_id" checked value="{{address.id}}">
                    {{address.consignee}}--{{address.phone}}--{{address.nation}}->{{address.province}}->{{address.city}}->{{address.country}}->{{address.street}}->{{address.intro}}
                    <br />
                {% else %}
                    <input type="radio" name="addr_id" value="{{address.id}}">
                    {{address.consignee}}--{{address.phone}}--{{address.nation}}->{{address.province}}->{{address.city}}->{{address.country}}->{{address.street}}->{{address.intro}}
                    <br />
                {% endif %}

                {% empty %}
                <div>没有收获地址，请<a href="{% url 'users:add_address' %}">添加</a></div>
                {% endfor %}

              </small>
          </h1>
        </div>
    <div class="page-header col-md-12">
          <h1>订单确认</h1>
        {% for sc in shop_cart_list %}
            <input type="hidden" name="sc" value="{{sc.id}}">
            {% endfor %}

        </div>

        <div class="page-header col-md-12 title">
          <h3>商品图片</h3>
          <h3>商品信息</h3>
          <h3>商品总价</h3>
        </div>

    <div class="col-md-12">
        {% for shop_cart in shop_cart_list %}
            <div class="media">
              <div class="media-left media-middle">
                <a href="#">
                  <img class="media-object" src="/{{shop_cart.goods.goodsimages_set.first.path}}" alt="...">
                </a>
              </div>
              <div class="media-body media-middle">
                <h3 class="media-heading">{{shop_cart.goods.name}}</h3>
                <h3 class="media-heading">价格：{{shop_cart.goods.price}}</h3>
                <h3 class="media-heading">数量：{{shop_cart.count}}</h3>
                <h3 class="media-heading total">小计：{{shop_cart.total}}</h3>
              </div>
        </div>
        {% endfor %}

    </div>
        <h3 align="right" style="color: red;">订单总价：{{total}}</h3>
        <button type="submit" class="btn btn-danger">提交订单</button>

</form>
</div>
{% endblock %}
{% block content %}{% endblock %}
{% block content2 %}{% endblock %}

myshopping/orders/templates/orders/order_info.html
{% extends 'base.html' %}
{% block lunbo %}
{% load static %}
<!--<link rel="stylesheet" href="{% static 'stores/css/store_add.css' %}">-->
<!--<link rel="stylesheet" href="{% static 'stores/css/store_add.css' %}">-->
<link rel="stylesheet" href="{% static 'orders/css/order_confirm.css'%}">
<div class="container">
    <div class="page-header col-md-12">
          <h1>订单信息</h1>
            <h3>订单编号：{{order.id}}</h3>
            <h3>下单时间：{{order.order_time|date:'Y-m-d G:i:s'}}</h3>
            <h3>收货地址：{{order.address}}</h3>
            <h3>总计金额：{{order.total}}</h3>
        </div>
    <div class="row">
        {% for orderitem in order.myorderitem_set.all %}
          <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
              <img src="/{{orderitem.goods_img}}" alt="...">
              <div class="caption">
                <h3>{{orderitem.goods_name}}</h3>
                <p>价格：{{orderitem.goods_price}}</p>
                <p>数量：{{orderitem.goods_count}}</p>
                <p>小计金额：{{orderitem.goods_subtotal}}</p>
                <!--<p><a href="{% url 'common:index' %}" class="btn btn-primary" role="button">继续购买</a> </p>-->
              </div>
            </div>
          </div>
             {% empty %}
                <h3>没有购买商品 <a href="{% url 'common:index' %}">购买</a></h3>
            {% endfor %}
    </div>

</div>
{% endblock %}
{% block content %}{% endblock %}
{% block content2 %}{% endblock %}

myshopping/orders/templates/orders/order_list.html
{% extends 'base.html'%}
{% block lunbo %}
{% load static %}
<link rel="stylesheet" href="{% static 'users/css/userinfo.css' %}">
<div class="container userinfo1">
    <div class="row">
        <div class="col-md-12">
            <div class="col-md-3">
                <div class="panel panel-default pan1">
                  <div class="panel-body">
                    <h3 class="panel-title"><i class="glyphicon glyphicon-user"></i> adiCLUB 账户</h3>
                  </div>
                  <div class="panel-heading">
                    <h3 class="panel-title tit1">个人信息</h3>
                  </div>
                  <div class="panel-body">
                    <ul class="u1">
                        <li class="u1l"><a class="u1la" href="">我的账户首页</a></li>
                        <li class="u1l"><a class="u1la" href="{% url 'users:user_info' %}">我的个人信息</a></li>
                        <li class="u1l"><a class="u1la" href="{% url 'users:address_list' %}">我的地址薄</a></li>
                        <li class="u1l"><a class="u1la" href="{% url 'users:add_address' %}">添加收货地址</a></li>
                        <li class="u1l"><a class="u1la" href="">我的积分</a></li>
                        <li class="u1l"><a class="u1la" href="">我的优惠卷</a></li>
                        <li class="u1l"><a class="u1la" href="">我的订阅</a></li>
                    </ul>
                  </div>
                  <div class="panel-heading">
                    <h3 class="panel-title tit1">订单信息</h3>
                  </div>
                  <div class="panel-body">
                    <ul class="u1">
                        <li class="u1l"><a class="u1la" href="{% url 'orders:order_list' %}">我的订单</a></li>
                        <li class="u1l"><a class="u1la" href="">我的退单</a></li>
                    </ul>
                  </div>
                  <div class="panel-heading">
                    <h3 class="panel-title tit1">帮助</h3>
                  </div>
                  <div class="panel-body">
                    <ul class="u1">
                        <li class="u1l"><a class="u1la" href="">关于订单</a></li>
                        <li class="u1l"><a class="u1la" href="">关于支付</a></li>
                        <li class="u1l"><a class="u1la" href="">我物流配送</a></li>
                        <li class="u1l"><a class="u1la" href="">退货退款</a></li>
                        <li class="u1l"><a class="u1la" href="">会员规则</a></li>
                        <li class="u1l"><a class="u1la" href="">关于adiCLUB</a></li>
                    </ul>
                  </div>
            </div>
            </div>
<!--=================================================================-->
            <div class="col-md-9">
                <div class="panel panel-default pan1">
                  <div class="panel-heading">
                    <h3 class="panel-title tit1">我的订单</h3>
                  </div>
                  <div class="panel-body">
                      <table border="0%" class="table table-hover">
                          <tr>
                              <td>订单编号</td>
                              <td>订单收货地址</td>
                              <td>订单时间</td>
                              <td>金额</td>
                              <td>查看详情</td>
                          </tr>
                          {% for order in order_list %}
                          <tr>
                              <td>{{order.id}}</td>
                              <td>{{order.address}}</td>
                              <td>{{order.order_time}}</td>
                              <td>{{order.total}}</td>
                              <td><a href="{% url 'orders:order_info' order.id %}">详情</a></td>
                          </tr>
                          {% empty %}
                      <p>你该没有订单</p>
                      <button class="btn "><a href="">去购买</a></button>
                      {% endfor %}
                      </table>

                  </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--========================================================================-->
{% endblock %}
{% block content %}{% endblock %}
{% block content2 %}{% endblock %}

myshopping/orders/templates/orders/order_pay.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>